/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AddToCartResult = { 'added' : Cart } |
  {
    'differentRestaurant' : {
      'requestedRestaurantId' : RestaurantId,
      'requestedRestaurantName' : string,
      'currentRestaurantName' : string,
      'currentRestaurantId' : RestaurantId,
    }
  };
export interface Address {
  'id' : AddressId,
  'street' : string,
  'city' : string,
  'barangay' : string,
  'addressLabel' : string,
  'isDefault' : boolean,
  'landmark' : [] | [string],
}
export type AddressId = bigint;
export interface AddressInput {
  'street' : string,
  'city' : string,
  'barangay' : string,
  'addressLabel' : string,
  'landmark' : [] | [string],
}
export interface Cart {
  'total' : Centavos,
  'deliveryFee' : Centavos,
  'restaurantId' : RestaurantId,
  'restaurantName' : string,
  'items' : Array<CartItem>,
  'subtotal' : Centavos,
}
export interface CartItem {
  'name' : string,
  'imageUrl' : [] | [ExternalBlob],
  'quantity' : bigint,
  'unitPrice' : Centavos,
  'menuItemId' : MenuItemId,
}
export interface Cell { 'value' : Value, 'name' : string }
export type Centavos = bigint;
export interface DashboardSummary {
  'ordersByStatus' : OrderStatusCounts,
  'restaurantCount' : bigint,
  'menuItemCount' : bigint,
}
export type DeliveryMinutes = bigint;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface MenuCategory { 'category' : string, 'items' : Array<MenuItem> }
export interface MenuItem {
  'id' : MenuItemId,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'restaurantId' : RestaurantId,
  'imageUrl' : [] | [ExternalBlob],
  'category' : string,
  'price' : Centavos,
}
export type MenuItemId = bigint;
export interface MenuItemInput {
  'name' : string,
  'description' : string,
  'available' : boolean,
  'imageUrl' : [] | [ExternalBlob],
  'category' : string,
  'price' : Centavos,
}
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : Centavos,
  'paymentMethod' : PaymentMethod,
  'deliveryFee' : Centavos,
  'createdAt' : Timestamp,
  'deliveryNotes' : [] | [string],
  'estimatedDeliveryMinutes' : DeliveryMinutes,
  'restaurantId' : RestaurantId,
  'updatedAt' : Timestamp,
  'restaurantName' : string,
  'address' : Address,
  'items' : Array<OrderLine>,
  'orderNumber' : string,
  'subtotal' : Centavos,
}
export type OrderId = bigint;
export interface OrderLine {
  'name' : string,
  'quantity' : bigint,
  'unitPrice' : Centavos,
  'menuItemId' : MenuItemId,
}
export type OrderStatus = { 'preparing' : null } |
  { 'outForDelivery' : null } |
  { 'placed' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface OrderStatusCounts {
  'preparing' : bigint,
  'outForDelivery' : bigint,
  'placed' : bigint,
  'delivered' : bigint,
  'confirmed' : bigint,
}
export type PaymentMethod = { 'cashOnDelivery' : null } |
  { 'card' : null };
export interface PlaceOrderInput {
  'paymentMethod' : PaymentMethod,
  'deliveryNotes' : [] | [string],
  'restaurantId' : RestaurantId,
  'addressId' : AddressId,
}
export interface Restaurant {
  'id' : RestaurantId,
  'coverImageUrl' : [] | [ExternalBlob],
  'active' : boolean,
  'deliveryFee' : Centavos,
  'ratingCount' : bigint,
  'name' : string,
  'estimatedDeliveryMinutes' : DeliveryMinutes,
  'description' : string,
  'cuisine' : string,
  'rating' : bigint,
  'operatingHours' : string,
  'promoLabel' : [] | [string],
}
export interface RestaurantDetail {
  'menu' : Array<MenuItem>,
  'restaurant' : Restaurant,
}
export interface RestaurantFilter {
  'minRating' : [] | [bigint],
  'maxDeliveryFee' : [] | [Centavos],
  'sort' : [] | [RestaurantSort],
  'maxPrice' : [] | [Centavos],
  'searchTerm' : [] | [string],
  'cuisine' : [] | [string],
  'maxDeliveryMinutes' : [] | [DeliveryMinutes],
}
export type RestaurantId = bigint;
export interface RestaurantInput {
  'coverImageUrl' : [] | [ExternalBlob],
  'deliveryFee' : Centavos,
  'name' : string,
  'estimatedDeliveryMinutes' : DeliveryMinutes,
  'description' : string,
  'cuisine' : string,
  'operatingHours' : string,
  'promoLabel' : [] | [string],
}
export type RestaurantSort = { 'deliveryFee' : null } |
  { 'priceLowToHigh' : null } |
  { 'deliveryTime' : null } |
  { 'rating' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Add a saved address for the caller.
   */
  'addAddress' : ActorMethod<[AddressInput], Address>,
  /**
   * / Add a menu item to a restaurant (admin only).
   */
  'addMenuItem' : ActorMethod<[RestaurantId, MenuItemInput], [] | [MenuItem]>,
  /**
   * / Add a dish to the caller's cart, or report a restaurant conflict.
   */
  'addToCart' : ActorMethod<
    [RestaurantId, MenuItemId, bigint],
    AddToCartResult
  >,
  /**
   * / Advance an order to the next status (admin only).
   */
  'advanceOrderStatus' : ActorMethod<[OrderId], [] | [Order]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Empty the caller's cart.
   */
  'clearCart' : ActorMethod<[], undefined>,
  /**
   * / Create a restaurant (admin only).
   */
  'createRestaurant' : ActorMethod<[RestaurantInput], Restaurant>,
  /**
   * / Delete one of the caller's saved addresses.
   */
  'deleteAddress' : ActorMethod<[AddressId], boolean>,
  /**
   * / Delete a restaurant and its menu items (admin only).
   */
  'deleteRestaurant' : ActorMethod<[RestaurantId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Return the backend's behavioral API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Return the caller's current cart, if any.
   */
  'getCart' : ActorMethod<[], [] | [Cart]>,
  /**
   * / Dashboard summary counts (admin only).
   */
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  /**
   * / Group a restaurant's menu items by category.
   */
  'getMenuByCategory' : ActorMethod<[RestaurantId], Array<MenuCategory>>,
  /**
   * / Fetch one of the caller's orders by id.
   */
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  /**
   * / Fetch a restaurant with its full menu.
   */
  'getRestaurant' : ActorMethod<[RestaurantId], [] | [RestaurantDetail]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List the caller's saved addresses.
   */
  'listAddresses' : ActorMethod<[], Array<Address>>,
  /**
   * / List all orders, optionally filtered by status (admin only).
   */
  'listAllOrders' : ActorMethod<[[] | [OrderStatus]], Array<Order>>,
  /**
   * / List the caller's past orders, newest first.
   */
  'listOrders' : ActorMethod<[], Array<Order>>,
  /**
   * / List restaurants matching the given filter, sorted accordingly.
   */
  'listRestaurants' : ActorMethod<[RestaurantFilter], Array<Restaurant>>,
  /**
   * / Count of menu items (admin only).
   */
  'menuItemCount' : ActorMethod<[], bigint>,
  /**
   * / Count of orders grouped by status (admin only).
   */
  'ordersByStatus' : ActorMethod<[], OrderStatusCounts>,
  /**
   * / Place an order from the caller's current cart.
   */
  'placeOrder' : ActorMethod<[PlaceOrderInput], Order>,
  /**
   * / Remove a line from the caller's cart.
   */
  'removeCartItem' : ActorMethod<[MenuItemId], [] | [Cart]>,
  /**
   * / Remove a menu item (admin only).
   */
  'removeMenuItem' : ActorMethod<[MenuItemId], boolean>,
  /**
   * / Count of restaurants (admin only).
   */
  'restaurantCount' : ActorMethod<[], bigint>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Search restaurant names and dish names.
   */
  'searchRestaurants' : ActorMethod<[string], Array<Restaurant>>,
  /**
   * / Mark one of the caller's addresses as the default.
   */
  'setDefaultAddress' : ActorMethod<[AddressId], [] | [Address]>,
  /**
   * / Update one of the caller's saved addresses.
   */
  'updateAddress' : ActorMethod<[AddressId, AddressInput], [] | [Address]>,
  /**
   * / Set the quantity of a cart line; zero removes it.
   */
  'updateCartItem' : ActorMethod<[MenuItemId, bigint], [] | [Cart]>,
  /**
   * / Update a menu item (admin only).
   */
  'updateMenuItem' : ActorMethod<[MenuItemId, MenuItemInput], [] | [MenuItem]>,
  /**
   * / Update a restaurant (admin only).
   */
  'updateRestaurant' : ActorMethod<
    [RestaurantId, RestaurantInput],
    [] | [Restaurant]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];