/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const AddressInput = IDL.Record({
  'street' : IDL.Text,
  'city' : IDL.Text,
  'barangay' : IDL.Text,
  'addressLabel' : IDL.Text,
  'landmark' : IDL.Opt(IDL.Text),
});
export const AddressId = IDL.Nat;
export const Address = IDL.Record({
  'id' : AddressId,
  'street' : IDL.Text,
  'city' : IDL.Text,
  'barangay' : IDL.Text,
  'addressLabel' : IDL.Text,
  'isDefault' : IDL.Bool,
  'landmark' : IDL.Opt(IDL.Text),
});
export const RestaurantId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Centavos = IDL.Nat;
export const MenuItemInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Opt(ExternalBlob),
  'category' : IDL.Text,
  'price' : Centavos,
});
export const MenuItemId = IDL.Nat;
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'restaurantId' : RestaurantId,
  'imageUrl' : IDL.Opt(ExternalBlob),
  'category' : IDL.Text,
  'price' : Centavos,
});
export const CartItem = IDL.Record({
  'name' : IDL.Text,
  'imageUrl' : IDL.Opt(ExternalBlob),
  'quantity' : IDL.Nat,
  'unitPrice' : Centavos,
  'menuItemId' : MenuItemId,
});
export const Cart = IDL.Record({
  'total' : Centavos,
  'deliveryFee' : Centavos,
  'restaurantId' : RestaurantId,
  'restaurantName' : IDL.Text,
  'items' : IDL.Vec(CartItem),
  'subtotal' : Centavos,
});
export const AddToCartResult = IDL.Variant({
  'added' : Cart,
  'differentRestaurant' : IDL.Record({
    'requestedRestaurantId' : RestaurantId,
    'requestedRestaurantName' : IDL.Text,
    'currentRestaurantName' : IDL.Text,
    'currentRestaurantId' : RestaurantId,
  }),
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'placed' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cashOnDelivery' : IDL.Null,
  'card' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const DeliveryMinutes = IDL.Nat;
export const OrderLine = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : Centavos,
  'menuItemId' : MenuItemId,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'total' : Centavos,
  'paymentMethod' : PaymentMethod,
  'deliveryFee' : Centavos,
  'createdAt' : Timestamp,
  'deliveryNotes' : IDL.Opt(IDL.Text),
  'estimatedDeliveryMinutes' : DeliveryMinutes,
  'restaurantId' : RestaurantId,
  'updatedAt' : Timestamp,
  'restaurantName' : IDL.Text,
  'address' : Address,
  'items' : IDL.Vec(OrderLine),
  'orderNumber' : IDL.Text,
  'subtotal' : Centavos,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RestaurantInput = IDL.Record({
  'coverImageUrl' : IDL.Opt(ExternalBlob),
  'deliveryFee' : Centavos,
  'name' : IDL.Text,
  'estimatedDeliveryMinutes' : DeliveryMinutes,
  'description' : IDL.Text,
  'cuisine' : IDL.Text,
  'operatingHours' : IDL.Text,
  'promoLabel' : IDL.Opt(IDL.Text),
});
export const Restaurant = IDL.Record({
  'id' : RestaurantId,
  'coverImageUrl' : IDL.Opt(ExternalBlob),
  'active' : IDL.Bool,
  'deliveryFee' : Centavos,
  'ratingCount' : IDL.Nat,
  'name' : IDL.Text,
  'estimatedDeliveryMinutes' : DeliveryMinutes,
  'description' : IDL.Text,
  'cuisine' : IDL.Text,
  'rating' : IDL.Nat,
  'operatingHours' : IDL.Text,
  'promoLabel' : IDL.Opt(IDL.Text),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const OrderStatusCounts = IDL.Record({
  'preparing' : IDL.Nat,
  'outForDelivery' : IDL.Nat,
  'placed' : IDL.Nat,
  'delivered' : IDL.Nat,
  'confirmed' : IDL.Nat,
});
export const DashboardSummary = IDL.Record({
  'ordersByStatus' : OrderStatusCounts,
  'restaurantCount' : IDL.Nat,
  'menuItemCount' : IDL.Nat,
});
export const MenuCategory = IDL.Record({
  'category' : IDL.Text,
  'items' : IDL.Vec(MenuItem),
});
export const RestaurantDetail = IDL.Record({
  'menu' : IDL.Vec(MenuItem),
  'restaurant' : Restaurant,
});
export const RestaurantSort = IDL.Variant({
  'deliveryFee' : IDL.Null,
  'priceLowToHigh' : IDL.Null,
  'deliveryTime' : IDL.Null,
  'rating' : IDL.Null,
});
export const RestaurantFilter = IDL.Record({
  'minRating' : IDL.Opt(IDL.Nat),
  'maxDeliveryFee' : IDL.Opt(Centavos),
  'sort' : IDL.Opt(RestaurantSort),
  'maxPrice' : IDL.Opt(Centavos),
  'searchTerm' : IDL.Opt(IDL.Text),
  'cuisine' : IDL.Opt(IDL.Text),
  'maxDeliveryMinutes' : IDL.Opt(DeliveryMinutes),
});
export const PlaceOrderInput = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'deliveryNotes' : IDL.Opt(IDL.Text),
  'restaurantId' : RestaurantId,
  'addressId' : AddressId,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addAddress' : IDL.Func([AddressInput], [Address], []),
  'addMenuItem' : IDL.Func(
      [RestaurantId, MenuItemInput],
      [IDL.Opt(MenuItem)],
      [],
    ),
  'addToCart' : IDL.Func(
      [RestaurantId, MenuItemId, IDL.Nat],
      [AddToCartResult],
      [],
    ),
  'advanceOrderStatus' : IDL.Func([OrderId], [IDL.Opt(Order)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createRestaurant' : IDL.Func([RestaurantInput], [Restaurant], []),
  'deleteAddress' : IDL.Func([AddressId], [IDL.Bool], []),
  'deleteRestaurant' : IDL.Func([RestaurantId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Opt(Cart)], ['query']),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getMenuByCategory' : IDL.Func(
      [RestaurantId],
      [IDL.Vec(MenuCategory)],
      ['query'],
    ),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getRestaurant' : IDL.Func(
      [RestaurantId],
      [IDL.Opt(RestaurantDetail)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAddresses' : IDL.Func([], [IDL.Vec(Address)], ['query']),
  'listAllOrders' : IDL.Func(
      [IDL.Opt(OrderStatus)],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listRestaurants' : IDL.Func(
      [RestaurantFilter],
      [IDL.Vec(Restaurant)],
      ['query'],
    ),
  'menuItemCount' : IDL.Func([], [IDL.Nat], ['query']),
  'ordersByStatus' : IDL.Func([], [OrderStatusCounts], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderInput], [Order], []),
  'removeCartItem' : IDL.Func([MenuItemId], [IDL.Opt(Cart)], []),
  'removeMenuItem' : IDL.Func([MenuItemId], [IDL.Bool], []),
  'restaurantCount' : IDL.Func([], [IDL.Nat], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchRestaurants' : IDL.Func([IDL.Text], [IDL.Vec(Restaurant)], ['query']),
  'setDefaultAddress' : IDL.Func([AddressId], [IDL.Opt(Address)], []),
  'updateAddress' : IDL.Func([AddressId, AddressInput], [IDL.Opt(Address)], []),
  'updateCartItem' : IDL.Func([MenuItemId, IDL.Nat], [IDL.Opt(Cart)], []),
  'updateMenuItem' : IDL.Func(
      [MenuItemId, MenuItemInput],
      [IDL.Opt(MenuItem)],
      [],
    ),
  'updateRestaurant' : IDL.Func(
      [RestaurantId, RestaurantInput],
      [IDL.Opt(Restaurant)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const AddressInput = IDL.Record({
    'street' : IDL.Text,
    'city' : IDL.Text,
    'barangay' : IDL.Text,
    'addressLabel' : IDL.Text,
    'landmark' : IDL.Opt(IDL.Text),
  });
  const AddressId = IDL.Nat;
  const Address = IDL.Record({
    'id' : AddressId,
    'street' : IDL.Text,
    'city' : IDL.Text,
    'barangay' : IDL.Text,
    'addressLabel' : IDL.Text,
    'isDefault' : IDL.Bool,
    'landmark' : IDL.Opt(IDL.Text),
  });
  const RestaurantId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Centavos = IDL.Nat;
  const MenuItemInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Opt(ExternalBlob),
    'category' : IDL.Text,
    'price' : Centavos,
  });
  const MenuItemId = IDL.Nat;
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'restaurantId' : RestaurantId,
    'imageUrl' : IDL.Opt(ExternalBlob),
    'category' : IDL.Text,
    'price' : Centavos,
  });
  const CartItem = IDL.Record({
    'name' : IDL.Text,
    'imageUrl' : IDL.Opt(ExternalBlob),
    'quantity' : IDL.Nat,
    'unitPrice' : Centavos,
    'menuItemId' : MenuItemId,
  });
  const Cart = IDL.Record({
    'total' : Centavos,
    'deliveryFee' : Centavos,
    'restaurantId' : RestaurantId,
    'restaurantName' : IDL.Text,
    'items' : IDL.Vec(CartItem),
    'subtotal' : Centavos,
  });
  const AddToCartResult = IDL.Variant({
    'added' : Cart,
    'differentRestaurant' : IDL.Record({
      'requestedRestaurantId' : RestaurantId,
      'requestedRestaurantName' : IDL.Text,
      'currentRestaurantName' : IDL.Text,
      'currentRestaurantId' : RestaurantId,
    }),
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'placed' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'cashOnDelivery' : IDL.Null,
    'card' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const DeliveryMinutes = IDL.Nat;
  const OrderLine = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : Centavos,
    'menuItemId' : MenuItemId,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'total' : Centavos,
    'paymentMethod' : PaymentMethod,
    'deliveryFee' : Centavos,
    'createdAt' : Timestamp,
    'deliveryNotes' : IDL.Opt(IDL.Text),
    'estimatedDeliveryMinutes' : DeliveryMinutes,
    'restaurantId' : RestaurantId,
    'updatedAt' : Timestamp,
    'restaurantName' : IDL.Text,
    'address' : Address,
    'items' : IDL.Vec(OrderLine),
    'orderNumber' : IDL.Text,
    'subtotal' : Centavos,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RestaurantInput = IDL.Record({
    'coverImageUrl' : IDL.Opt(ExternalBlob),
    'deliveryFee' : Centavos,
    'name' : IDL.Text,
    'estimatedDeliveryMinutes' : DeliveryMinutes,
    'description' : IDL.Text,
    'cuisine' : IDL.Text,
    'operatingHours' : IDL.Text,
    'promoLabel' : IDL.Opt(IDL.Text),
  });
  const Restaurant = IDL.Record({
    'id' : RestaurantId,
    'coverImageUrl' : IDL.Opt(ExternalBlob),
    'active' : IDL.Bool,
    'deliveryFee' : Centavos,
    'ratingCount' : IDL.Nat,
    'name' : IDL.Text,
    'estimatedDeliveryMinutes' : DeliveryMinutes,
    'description' : IDL.Text,
    'cuisine' : IDL.Text,
    'rating' : IDL.Nat,
    'operatingHours' : IDL.Text,
    'promoLabel' : IDL.Opt(IDL.Text),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const OrderStatusCounts = IDL.Record({
    'preparing' : IDL.Nat,
    'outForDelivery' : IDL.Nat,
    'placed' : IDL.Nat,
    'delivered' : IDL.Nat,
    'confirmed' : IDL.Nat,
  });
  const DashboardSummary = IDL.Record({
    'ordersByStatus' : OrderStatusCounts,
    'restaurantCount' : IDL.Nat,
    'menuItemCount' : IDL.Nat,
  });
  const MenuCategory = IDL.Record({
    'category' : IDL.Text,
    'items' : IDL.Vec(MenuItem),
  });
  const RestaurantDetail = IDL.Record({
    'menu' : IDL.Vec(MenuItem),
    'restaurant' : Restaurant,
  });
  const RestaurantSort = IDL.Variant({
    'deliveryFee' : IDL.Null,
    'priceLowToHigh' : IDL.Null,
    'deliveryTime' : IDL.Null,
    'rating' : IDL.Null,
  });
  const RestaurantFilter = IDL.Record({
    'minRating' : IDL.Opt(IDL.Nat),
    'maxDeliveryFee' : IDL.Opt(Centavos),
    'sort' : IDL.Opt(RestaurantSort),
    'maxPrice' : IDL.Opt(Centavos),
    'searchTerm' : IDL.Opt(IDL.Text),
    'cuisine' : IDL.Opt(IDL.Text),
    'maxDeliveryMinutes' : IDL.Opt(DeliveryMinutes),
  });
  const PlaceOrderInput = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'deliveryNotes' : IDL.Opt(IDL.Text),
    'restaurantId' : RestaurantId,
    'addressId' : AddressId,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addAddress' : IDL.Func([AddressInput], [Address], []),
    'addMenuItem' : IDL.Func(
        [RestaurantId, MenuItemInput],
        [IDL.Opt(MenuItem)],
        [],
      ),
    'addToCart' : IDL.Func(
        [RestaurantId, MenuItemId, IDL.Nat],
        [AddToCartResult],
        [],
      ),
    'advanceOrderStatus' : IDL.Func([OrderId], [IDL.Opt(Order)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createRestaurant' : IDL.Func([RestaurantInput], [Restaurant], []),
    'deleteAddress' : IDL.Func([AddressId], [IDL.Bool], []),
    'deleteRestaurant' : IDL.Func([RestaurantId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Opt(Cart)], ['query']),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getMenuByCategory' : IDL.Func(
        [RestaurantId],
        [IDL.Vec(MenuCategory)],
        ['query'],
      ),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getRestaurant' : IDL.Func(
        [RestaurantId],
        [IDL.Opt(RestaurantDetail)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAddresses' : IDL.Func([], [IDL.Vec(Address)], ['query']),
    'listAllOrders' : IDL.Func(
        [IDL.Opt(OrderStatus)],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'listOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listRestaurants' : IDL.Func(
        [RestaurantFilter],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'menuItemCount' : IDL.Func([], [IDL.Nat], ['query']),
    'ordersByStatus' : IDL.Func([], [OrderStatusCounts], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderInput], [Order], []),
    'removeCartItem' : IDL.Func([MenuItemId], [IDL.Opt(Cart)], []),
    'removeMenuItem' : IDL.Func([MenuItemId], [IDL.Bool], []),
    'restaurantCount' : IDL.Func([], [IDL.Nat], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchRestaurants' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Restaurant)],
        ['query'],
      ),
    'setDefaultAddress' : IDL.Func([AddressId], [IDL.Opt(Address)], []),
    'updateAddress' : IDL.Func(
        [AddressId, AddressInput],
        [IDL.Opt(Address)],
        [],
      ),
    'updateCartItem' : IDL.Func([MenuItemId, IDL.Nat], [IDL.Opt(Cart)], []),
    'updateMenuItem' : IDL.Func(
        [MenuItemId, MenuItemInput],
        [IDL.Opt(MenuItem)],
        [],
      ),
    'updateRestaurant' : IDL.Func(
        [RestaurantId, RestaurantInput],
        [IDL.Opt(Restaurant)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };