/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type AddToCartResult = {
    __kind__: "added";
    added: Cart;
} | {
    __kind__: "differentRestaurant";
    differentRestaurant: {
        requestedRestaurantId: RestaurantId;
        requestedRestaurantName: string;
        currentRestaurantName: string;
        currentRestaurantId: RestaurantId;
    };
};
export interface Address {
    id: AddressId;
    street: string;
    city: string;
    barangay: string;
    addressLabel: string;
    isDefault: boolean;
    landmark?: string;
}
export type AddressId = bigint;
export interface AddressInput {
    street: string;
    city: string;
    barangay: string;
    addressLabel: string;
    landmark?: string;
}
export interface Cart {
    total: Centavos;
    deliveryFee: Centavos;
    restaurantId: RestaurantId;
    restaurantName: string;
    items: Array<CartItem>;
    subtotal: Centavos;
}
export interface CartItem {
    name: string;
    imageUrl?: ExternalBlob;
    quantity: bigint;
    unitPrice: Centavos;
    menuItemId: MenuItemId;
}
export interface Cell {
    value: Value;
    name: string;
}
export type Centavos = bigint;
export interface DashboardSummary {
    ordersByStatus: OrderStatusCounts;
    restaurantCount: bigint;
    menuItemCount: bigint;
}
export type DeliveryMinutes = bigint;
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface MenuCategory {
    category: string;
    items: Array<MenuItem>;
}
export interface MenuItem {
    id: MenuItemId;
    name: string;
    description: string;
    available: boolean;
    restaurantId: RestaurantId;
    imageUrl?: ExternalBlob;
    category: string;
    price: Centavos;
}
export type MenuItemId = bigint;
export interface MenuItemInput {
    name: string;
    description: string;
    available: boolean;
    imageUrl?: ExternalBlob;
    category: string;
    price: Centavos;
}
export interface Order {
    id: OrderId;
    status: OrderStatus;
    total: Centavos;
    paymentMethod: PaymentMethod;
    deliveryFee: Centavos;
    createdAt: Timestamp;
    deliveryNotes?: string;
    estimatedDeliveryMinutes: DeliveryMinutes;
    restaurantId: RestaurantId;
    updatedAt: Timestamp;
    restaurantName: string;
    address: Address;
    items: Array<OrderLine>;
    orderNumber: string;
    subtotal: Centavos;
}
export type OrderId = bigint;
export interface OrderLine {
    name: string;
    quantity: bigint;
    unitPrice: Centavos;
    menuItemId: MenuItemId;
}
export interface OrderStatusCounts {
    preparing: bigint;
    outForDelivery: bigint;
    placed: bigint;
    delivered: bigint;
    confirmed: bigint;
}
export interface PlaceOrderInput {
    paymentMethod: PaymentMethod;
    deliveryNotes?: string;
    restaurantId: RestaurantId;
    addressId: AddressId;
}
export interface Restaurant {
    id: RestaurantId;
    coverImageUrl?: ExternalBlob;
    active: boolean;
    deliveryFee: Centavos;
    ratingCount: bigint;
    name: string;
    estimatedDeliveryMinutes: DeliveryMinutes;
    description: string;
    cuisine: string;
    rating: bigint;
    operatingHours: string;
    promoLabel?: string;
}
export interface RestaurantDetail {
    menu: Array<MenuItem>;
    restaurant: Restaurant;
}
export interface RestaurantFilter {
    minRating?: bigint;
    maxDeliveryFee?: Centavos;
    sort?: RestaurantSort;
    maxPrice?: Centavos;
    searchTerm?: string;
    cuisine?: string;
    maxDeliveryMinutes?: DeliveryMinutes;
}
export type RestaurantId = bigint;
export interface RestaurantInput {
    coverImageUrl?: ExternalBlob;
    deliveryFee: Centavos;
    name: string;
    estimatedDeliveryMinutes: DeliveryMinutes;
    description: string;
    cuisine: string;
    operatingHours: string;
    promoLabel?: string;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Timestamp = bigint;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum OrderStatus {
    preparing = "preparing",
    outForDelivery = "outForDelivery",
    placed = "placed",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum PaymentMethod {
    cashOnDelivery = "cashOnDelivery",
    card = "card"
}
export enum RestaurantSort {
    deliveryFee = "deliveryFee",
    priceLowToHigh = "priceLowToHigh",
    deliveryTime = "deliveryTime",
    rating = "rating"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Add a saved address for the caller.
     */
    addAddress(input: AddressInput): Promise<Address>;
    /**
     * / Add a menu item to a restaurant (admin only).
     */
    addMenuItem(restaurantId: RestaurantId, input: MenuItemInput): Promise<MenuItem | null>;
    /**
     * / Add a dish to the caller's cart, or report a restaurant conflict.
     */
    addToCart(restaurantId: RestaurantId, menuItemId: MenuItemId, quantity: bigint): Promise<AddToCartResult>;
    /**
     * / Advance an order to the next status (admin only).
     */
    advanceOrderStatus(id: OrderId): Promise<Order | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Empty the caller's cart.
     */
    clearCart(): Promise<void>;
    /**
     * / Create a restaurant (admin only).
     */
    createRestaurant(input: RestaurantInput): Promise<Restaurant>;
    /**
     * / Delete one of the caller's saved addresses.
     */
    deleteAddress(id: AddressId): Promise<boolean>;
    /**
     * / Delete a restaurant and its menu items (admin only).
     */
    deleteRestaurant(id: RestaurantId): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Return the backend's behavioral API documentation as Markdown.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Return the caller's current cart, if any.
     */
    getCart(): Promise<Cart | null>;
    /**
     * / Dashboard summary counts (admin only).
     */
    getDashboardSummary(): Promise<DashboardSummary>;
    /**
     * / Group a restaurant's menu items by category.
     */
    getMenuByCategory(id: RestaurantId): Promise<Array<MenuCategory>>;
    /**
     * / Fetch one of the caller's orders by id.
     */
    getOrder(id: OrderId): Promise<Order | null>;
    /**
     * / Fetch a restaurant with its full menu.
     */
    getRestaurant(id: RestaurantId): Promise<RestaurantDetail | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List the caller's saved addresses.
     */
    listAddresses(): Promise<Array<Address>>;
    /**
     * / List all orders, optionally filtered by status (admin only).
     */
    listAllOrders(status: OrderStatus | null): Promise<Array<Order>>;
    /**
     * / List the caller's past orders, newest first.
     */
    listOrders(): Promise<Array<Order>>;
    /**
     * / List restaurants matching the given filter, sorted accordingly.
     */
    listRestaurants(filter: RestaurantFilter): Promise<Array<Restaurant>>;
    /**
     * / Count of menu items (admin only).
     */
    menuItemCount(): Promise<bigint>;
    /**
     * / Count of orders grouped by status (admin only).
     */
    ordersByStatus(): Promise<OrderStatusCounts>;
    /**
     * / Place an order from the caller's current cart.
     */
    placeOrder(input: PlaceOrderInput): Promise<Order>;
    /**
     * / Remove a line from the caller's cart.
     */
    removeCartItem(menuItemId: MenuItemId): Promise<Cart | null>;
    /**
     * / Remove a menu item (admin only).
     */
    removeMenuItem(itemId: MenuItemId): Promise<boolean>;
    /**
     * / Count of restaurants (admin only).
     */
    restaurantCount(): Promise<bigint>;
    schema(): Promise<string>;
    /**
     * / Search restaurant names and dish names.
     */
    searchRestaurants(term: string): Promise<Array<Restaurant>>;
    /**
     * / Mark one of the caller's addresses as the default.
     */
    setDefaultAddress(id: AddressId): Promise<Address | null>;
    /**
     * / Update one of the caller's saved addresses.
     */
    updateAddress(id: AddressId, input: AddressInput): Promise<Address | null>;
    /**
     * / Set the quantity of a cart line; zero removes it.
     */
    updateCartItem(menuItemId: MenuItemId, quantity: bigint): Promise<Cart | null>;
    /**
     * / Update a menu item (admin only).
     */
    updateMenuItem(itemId: MenuItemId, input: MenuItemInput): Promise<MenuItem | null>;
    /**
     * / Update a restaurant (admin only).
     */
    updateRestaurant(id: RestaurantId, input: RestaurantInput): Promise<Restaurant | null>;
}
import type { AddToCartResult as _AddToCartResult, Address as _Address, AddressId as _AddressId, AddressInput as _AddressInput, Cart as _Cart, CartItem as _CartItem, Cell as _Cell, Centavos as _Centavos, DeliveryMinutes as _DeliveryMinutes, Error as _Error, ExternalBlob as _ExternalBlob, MenuCategory as _MenuCategory, MenuItem as _MenuItem, MenuItemId as _MenuItemId, MenuItemInput as _MenuItemInput, Order as _Order, OrderId as _OrderId, OrderLine as _OrderLine, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, PlaceOrderInput as _PlaceOrderInput, Restaurant as _Restaurant, RestaurantDetail as _RestaurantDetail, RestaurantFilter as _RestaurantFilter, RestaurantId as _RestaurantId, RestaurantInput as _RestaurantInput, RestaurantSort as _RestaurantSort, Result as _Result, Result__1 as _Result__1, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addAddress(arg0: AddressInput): Promise<Address> {
        if (this.processError) {
            try {
                const result = await this.actor.addAddress(to_candid_AddressInput_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Address_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAddress(to_candid_AddressInput_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Address_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async addMenuItem(arg0: RestaurantId, arg1: MenuItemInput): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0, await to_candid_MenuItemInput_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0, await to_candid_MenuItemInput_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async addToCart(arg0: RestaurantId, arg1: MenuItemId, arg2: bigint): Promise<AddToCartResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1, arg2);
                return from_candid_AddToCartResult_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1, arg2);
            return from_candid_AddToCartResult_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async advanceOrderStatus(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.advanceOrderStatus(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.advanceOrderStatus(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async createRestaurant(arg0: RestaurantInput): Promise<Restaurant> {
        if (this.processError) {
            try {
                const result = await this.actor.createRestaurant(await to_candid_RestaurantInput_n38(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Restaurant_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRestaurant(await to_candid_RestaurantInput_n38(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Restaurant_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAddress(arg0: AddressId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAddress(arg0);
            return result;
        }
    }
    async deleteRestaurant(arg0: RestaurantId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRestaurant(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRestaurant(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Cart | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardSummary(): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return result;
        }
    }
    async getMenuByCategory(arg0: RestaurantId): Promise<Array<MenuCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuByCategory(arg0);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuByCategory(arg0);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurant(arg0: RestaurantId): Promise<RestaurantDetail | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurant(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurant(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAddresses(): Promise<Array<Address>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAddresses();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAddresses();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllOrders(arg0: OrderStatus | null): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllOrders(to_candid_opt_n60(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllOrders(to_candid_opt_n60(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrders();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrders();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRestaurants(arg0: RestaurantFilter): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRestaurants(to_candid_RestaurantFilter_n63(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRestaurants(to_candid_RestaurantFilter_n63(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async menuItemCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.menuItemCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.menuItemCount();
            return result;
        }
    }
    async ordersByStatus(): Promise<OrderStatusCounts> {
        if (this.processError) {
            try {
                const result = await this.actor.ordersByStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ordersByStatus();
            return result;
        }
    }
    async placeOrder(arg0: PlaceOrderInput): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_PlaceOrderInput_n67(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_PlaceOrderInput_n67(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeCartItem(arg0: MenuItemId): Promise<Cart | null> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCartItem(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCartItem(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeMenuItem(arg0: MenuItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMenuItem(arg0);
            return result;
        }
    }
    async restaurantCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.restaurantCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.restaurantCount();
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchRestaurants(arg0: string): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRestaurants(arg0);
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRestaurants(arg0);
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDefaultAddress(arg0: AddressId): Promise<Address | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setDefaultAddress(arg0);
                return from_candid_opt_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDefaultAddress(arg0);
            return from_candid_opt_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAddress(arg0: AddressId, arg1: AddressInput): Promise<Address | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAddress(arg0, to_candid_AddressInput_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAddress(arg0, to_candid_AddressInput_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCartItem(arg0: MenuItemId, arg1: bigint): Promise<Cart | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItem(arg0, arg1);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItem(arg0, arg1);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMenuItem(arg0: MenuItemId, arg1: MenuItemInput): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, await to_candid_MenuItemInput_n17(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, await to_candid_MenuItemInput_n17(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRestaurant(arg0: RestaurantId, arg1: RestaurantInput): Promise<Restaurant | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRestaurant(arg0, await to_candid_RestaurantInput_n38(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRestaurant(arg0, await to_candid_RestaurantInput_n38(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n71(this._uploadFile, this._downloadFile, result);
        }
    }
}
async function from_candid_AddToCartResult_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AddToCartResult): Promise<AddToCartResult> {
    return await from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Address_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Address): Address {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_CartItem_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): Promise<CartItem> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_Cart_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cart): Promise<Cart> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_MenuCategory_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuCategory): Promise<MenuCategory> {
    return await from_candid_record_n54(_uploadFile, _downloadFile, value);
}
async function from_candid_MenuItem_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): Promise<MenuItem> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return "preparing" in value ? OrderStatus.preparing : "outForDelivery" in value ? OrderStatus.outForDelivery : "placed" in value ? OrderStatus.placed : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_Order_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return "cashOnDelivery" in value ? PaymentMethod.cashOnDelivery : "card" in value ? PaymentMethod.card : value;
}
async function from_candid_RestaurantDetail_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RestaurantDetail): Promise<RestaurantDetail> {
    return await from_candid_record_n58(_uploadFile, _downloadFile, value);
}
async function from_candid_Restaurant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Restaurant): Promise<Restaurant> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItem]): Promise<MenuItem | null> {
    return value.length === 0 ? null : await from_candid_MenuItem_n21(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n33(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Cart]): Promise<Cart | null> {
    return value.length === 0 ? null : await from_candid_Cart_n27(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RestaurantDetail]): Promise<RestaurantDetail | null> {
    return value.length === 0 ? null : await from_candid_RestaurantDetail_n57(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Address]): Address | null {
    return value.length === 0 ? null : from_candid_Address_n14(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Restaurant]): Promise<Restaurant | null> {
    return value.length === 0 ? null : await from_candid_Restaurant_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AddressId;
    street: string;
    city: string;
    barangay: string;
    addressLabel: string;
    isDefault: boolean;
    landmark: [] | [string];
}): {
    id: AddressId;
    street: string;
    city: string;
    barangay: string;
    addressLabel: string;
    isDefault: boolean;
    landmark?: string;
} {
    return {
        id: value.id,
        street: value.street,
        city: value.city,
        barangay: value.barangay,
        addressLabel: value.addressLabel,
        isDefault: value.isDefault,
        landmark: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.landmark))
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MenuItemId;
    name: string;
    description: string;
    available: boolean;
    restaurantId: _RestaurantId;
    imageUrl: [] | [_ExternalBlob];
    category: string;
    price: _Centavos;
}): Promise<{
    id: MenuItemId;
    name: string;
    description: string;
    available: boolean;
    restaurantId: RestaurantId;
    imageUrl?: ExternalBlob;
    category: string;
    price: Centavos;
}> {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        available: value.available,
        restaurantId: value.restaurantId,
        imageUrl: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.imageUrl)),
        category: value.category,
        price: value.price
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: _Centavos;
    deliveryFee: _Centavos;
    restaurantId: _RestaurantId;
    restaurantName: string;
    items: Array<_CartItem>;
    subtotal: _Centavos;
}): Promise<{
    total: Centavos;
    deliveryFee: Centavos;
    restaurantId: RestaurantId;
    restaurantName: string;
    items: Array<CartItem>;
    subtotal: Centavos;
}> {
    return {
        total: value.total,
        deliveryFee: value.deliveryFee,
        restaurantId: value.restaurantId,
        restaurantName: value.restaurantName,
        items: await from_candid_vec_n29(_uploadFile, _downloadFile, value.items),
        subtotal: value.subtotal
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    imageUrl: [] | [_ExternalBlob];
    quantity: bigint;
    unitPrice: _Centavos;
    menuItemId: _MenuItemId;
}): Promise<{
    name: string;
    imageUrl?: ExternalBlob;
    quantity: bigint;
    unitPrice: Centavos;
    menuItemId: MenuItemId;
}> {
    return {
        name: value.name,
        imageUrl: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.imageUrl)),
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        menuItemId: value.menuItemId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    total: _Centavos;
    paymentMethod: _PaymentMethod;
    deliveryFee: _Centavos;
    createdAt: _Timestamp;
    deliveryNotes: [] | [string];
    estimatedDeliveryMinutes: _DeliveryMinutes;
    restaurantId: _RestaurantId;
    updatedAt: _Timestamp;
    restaurantName: string;
    address: _Address;
    items: Array<_OrderLine>;
    orderNumber: string;
    subtotal: _Centavos;
}): {
    id: OrderId;
    status: OrderStatus;
    total: Centavos;
    paymentMethod: PaymentMethod;
    deliveryFee: Centavos;
    createdAt: Timestamp;
    deliveryNotes?: string;
    estimatedDeliveryMinutes: DeliveryMinutes;
    restaurantId: RestaurantId;
    updatedAt: Timestamp;
    restaurantName: string;
    address: Address;
    items: Array<OrderLine>;
    orderNumber: string;
    subtotal: Centavos;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n35(_uploadFile, _downloadFile, value.status),
        total: value.total,
        paymentMethod: from_candid_PaymentMethod_n36(_uploadFile, _downloadFile, value.paymentMethod),
        deliveryFee: value.deliveryFee,
        createdAt: value.createdAt,
        deliveryNotes: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.deliveryNotes)),
        estimatedDeliveryMinutes: value.estimatedDeliveryMinutes,
        restaurantId: value.restaurantId,
        updatedAt: value.updatedAt,
        restaurantName: value.restaurantName,
        address: from_candid_Address_n14(_uploadFile, _downloadFile, value.address),
        items: value.items,
        orderNumber: value.orderNumber,
        subtotal: value.subtotal
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RestaurantId;
    coverImageUrl: [] | [_ExternalBlob];
    active: boolean;
    deliveryFee: _Centavos;
    ratingCount: bigint;
    name: string;
    estimatedDeliveryMinutes: _DeliveryMinutes;
    description: string;
    cuisine: string;
    rating: bigint;
    operatingHours: string;
    promoLabel: [] | [string];
}): Promise<{
    id: RestaurantId;
    coverImageUrl?: ExternalBlob;
    active: boolean;
    deliveryFee: Centavos;
    ratingCount: bigint;
    name: string;
    estimatedDeliveryMinutes: DeliveryMinutes;
    description: string;
    cuisine: string;
    rating: bigint;
    operatingHours: string;
    promoLabel?: string;
}> {
    return {
        id: value.id,
        coverImageUrl: record_opt_to_undefined(await from_candid_opt_n23(_uploadFile, _downloadFile, value.coverImageUrl)),
        active: value.active,
        deliveryFee: value.deliveryFee,
        ratingCount: value.ratingCount,
        name: value.name,
        estimatedDeliveryMinutes: value.estimatedDeliveryMinutes,
        description: value.description,
        cuisine: value.cuisine,
        rating: value.rating,
        operatingHours: value.operatingHours,
        promoLabel: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.promoLabel))
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n44(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n48(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category: string;
    items: Array<_MenuItem>;
}): Promise<{
    category: string;
    items: Array<MenuItem>;
}> {
    return {
        category: value.category,
        items: await from_candid_vec_n55(_uploadFile, _downloadFile, value.items)
    };
}
async function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    menu: Array<_MenuItem>;
    restaurant: _Restaurant;
}): Promise<{
    menu: Array<MenuItem>;
    restaurant: Restaurant;
}> {
    return {
        menu: await from_candid_vec_n55(_uploadFile, _downloadFile, value.menu),
        restaurant: await from_candid_Restaurant_n40(_uploadFile, _downloadFile, value.restaurant)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
async function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    added: _Cart;
} | {
    differentRestaurant: {
        requestedRestaurantId: _RestaurantId;
        requestedRestaurantName: string;
        currentRestaurantName: string;
        currentRestaurantId: _RestaurantId;
    };
}): Promise<{
    __kind__: "added";
    added: Cart;
} | {
    __kind__: "differentRestaurant";
    differentRestaurant: {
        requestedRestaurantId: RestaurantId;
        requestedRestaurantName: string;
        currentRestaurantName: string;
        currentRestaurantId: RestaurantId;
    };
}> {
    return "added" in value ? {
        __kind__: "added",
        added: await from_candid_Cart_n27(_uploadFile, _downloadFile, value.added)
    } : "differentRestaurant" in value ? {
        __kind__: "differentRestaurant",
        differentRestaurant: value.differentRestaurant
    } : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Promise<Array<CartItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CartItem_n30(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n46(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuCategory>): Promise<Array<MenuCategory>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MenuCategory_n53(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Promise<Array<MenuItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MenuItem_n21(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Address>): Array<Address> {
    return value.map((x)=>from_candid_Address_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n33(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Restaurant>): Promise<Array<Restaurant>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Restaurant_n40(_uploadFile, _downloadFile, x)));
}
function to_candid_AddressInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddressInput): _AddressInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_MenuItemInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItemInput): Promise<_MenuItemInput> {
    return await to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return value == OrderStatus.preparing ? {
        preparing: null
    } : value == OrderStatus.outForDelivery ? {
        outForDelivery: null
    } : value == OrderStatus.placed ? {
        placed: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_PaymentMethod_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return value == PaymentMethod.cashOnDelivery ? {
        cashOnDelivery: null
    } : value == PaymentMethod.card ? {
        card: null
    } : value;
}
function to_candid_PlaceOrderInput_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceOrderInput): _PlaceOrderInput {
    return to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_RestaurantFilter_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantFilter): _RestaurantFilter {
    return to_candid_record_n64(_uploadFile, _downloadFile, value);
}
async function to_candid_RestaurantInput_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantInput): Promise<_RestaurantInput> {
    return await to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_RestaurantSort_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RestaurantSort): _RestaurantSort {
    return value == RestaurantSort.deliveryFee ? {
        deliveryFee: null
    } : value == RestaurantSort.priceLowToHigh ? {
        priceLowToHigh: null
    } : value == RestaurantSort.deliveryTime ? {
        deliveryTime: null
    } : value == RestaurantSort.rating ? {
        rating: null
    } : value;
}
function to_candid_UserRole_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus | null): [] | [_OrderStatus] {
    return value === null ? candid_none() : candid_some(to_candid_OrderStatus_n61(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    street: string;
    city: string;
    barangay: string;
    addressLabel: string;
    landmark?: string;
}): {
    street: string;
    city: string;
    barangay: string;
    addressLabel: string;
    landmark: [] | [string];
} {
    return {
        street: value.street,
        city: value.city,
        barangay: value.barangay,
        addressLabel: value.addressLabel,
        landmark: value.landmark ? candid_some(value.landmark) : candid_none()
    };
}
async function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    available: boolean;
    imageUrl?: ExternalBlob;
    category: string;
    price: Centavos;
}): Promise<{
    name: string;
    description: string;
    available: boolean;
    imageUrl: [] | [_ExternalBlob];
    category: string;
    price: _Centavos;
}> {
    return {
        name: value.name,
        description: value.description,
        available: value.available,
        imageUrl: value.imageUrl ? candid_some(await to_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.imageUrl)) : candid_none(),
        category: value.category,
        price: value.price
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coverImageUrl?: ExternalBlob;
    deliveryFee: Centavos;
    name: string;
    estimatedDeliveryMinutes: DeliveryMinutes;
    description: string;
    cuisine: string;
    operatingHours: string;
    promoLabel?: string;
}): Promise<{
    coverImageUrl: [] | [_ExternalBlob];
    deliveryFee: _Centavos;
    name: string;
    estimatedDeliveryMinutes: _DeliveryMinutes;
    description: string;
    cuisine: string;
    operatingHours: string;
    promoLabel: [] | [string];
}> {
    return {
        coverImageUrl: value.coverImageUrl ? candid_some(await to_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.coverImageUrl)) : candid_none(),
        deliveryFee: value.deliveryFee,
        name: value.name,
        estimatedDeliveryMinutes: value.estimatedDeliveryMinutes,
        description: value.description,
        cuisine: value.cuisine,
        operatingHours: value.operatingHours,
        promoLabel: value.promoLabel ? candid_some(value.promoLabel) : candid_none()
    };
}
function to_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minRating?: bigint;
    maxDeliveryFee?: Centavos;
    sort?: RestaurantSort;
    maxPrice?: Centavos;
    searchTerm?: string;
    cuisine?: string;
    maxDeliveryMinutes?: DeliveryMinutes;
}): {
    minRating: [] | [bigint];
    maxDeliveryFee: [] | [_Centavos];
    sort: [] | [_RestaurantSort];
    maxPrice: [] | [_Centavos];
    searchTerm: [] | [string];
    cuisine: [] | [string];
    maxDeliveryMinutes: [] | [_DeliveryMinutes];
} {
    return {
        minRating: value.minRating ? candid_some(value.minRating) : candid_none(),
        maxDeliveryFee: value.maxDeliveryFee ? candid_some(value.maxDeliveryFee) : candid_none(),
        sort: value.sort ? candid_some(to_candid_RestaurantSort_n65(_uploadFile, _downloadFile, value.sort)) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        cuisine: value.cuisine ? candid_some(value.cuisine) : candid_none(),
        maxDeliveryMinutes: value.maxDeliveryMinutes ? candid_some(value.maxDeliveryMinutes) : candid_none()
    };
}
function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: PaymentMethod;
    deliveryNotes?: string;
    restaurantId: RestaurantId;
    addressId: AddressId;
}): {
    paymentMethod: _PaymentMethod;
    deliveryNotes: [] | [string];
    restaurantId: _RestaurantId;
    addressId: _AddressId;
} {
    return {
        paymentMethod: to_candid_PaymentMethod_n69(_uploadFile, _downloadFile, value.paymentMethod),
        deliveryNotes: value.deliveryNotes ? candid_some(value.deliveryNotes) : candid_none(),
        restaurantId: value.restaurantId,
        addressId: value.addressId
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
